### ISSUE TITLE
[공지] PR 올리는 방식 선택

### ISSUE THREAD

**Issue by bono039** [bono039/algorithm-study#9]
안녕하십니까 강한 스터디원분들!
PR 규칙, 어느 것이 더 편해보이십니까?

댓글로 의견을 남겨주세요!

<br/>

 **1.  문제마다 브랜치 따로 생성해서 PR 올림**
사례 : https://github.com/Stendhalsynd/baekjoon-algorithm-study/pulls

<br/>

**2.  PR 1개에 한 주차 문제 다 만들어둠**
사례 :  https://github.com/b1urrrr/Algorithm-Study/pull/597

**Comment by ahyun39** [comment]
**포함하고 싶은 내용 : 어려웠던 점 / 풀이 방식 / 새로 알게된 내용**

1번 방식이 더 편할 것 같다. 문제별로 pr을 올려야 보기에 편할 것 같다.
